server:
  port: 8085
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rpadilla5/PracticaExtra2.git
          searchPaths: config-file
          username: Rpadilla5
          password: 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
          default-label: master
  application:
    name: SpringServerConfig